export const spellDBCSchema = {
    ID: 'int32',
    School: 'int32',
    Category: 'int32',
    CastUI: 'int32',
    DispelType: 'int32',
    Mechanic: 'int32',
    Attributes: 'int32',
    AttributesEx: 'int32',
    AttributesEx_2: 'int32',
    AttributesEx_3: 'int32',
    AttributesEx_4: 'int32',
    ShapeshiftMask: 'int32',
    ShapeshiftExclude: 'int32',
    Targets: 'int32',
    TargetCreatureType: 'int32',
    RequiresSpellFocus: 'int32',
    CasterAuraState: 'int32',
    TargetAuraState: 'int32',
    CastingTimeIndex: 'int32',
    RecoveryTime: 'int32',
    CategoryRecoveryTime: 'int32',
    InterruptFlags: 'int32',
    AuraInterruptFlags: 'int32',
    ChannelInterruptFlags: 'int32',
    ProcTypeMask: 'int32',
    ProcChance: 'int32',
    ProcCharges: 'int32',
    MaxLevel: 'int32',
    BaseLevel: 'int32',
    SpellLevel: 'int32',
    DurationIndex: 'int32',
    PowerType: 'int32',
    ManaCost: 'int32',
    ManaCostPerLevel: 'int32',
    ManaCostPerSecond: 'int32',
    ManaCostPerSecondPerLevel: 'int32',
    RangeIndex: 'int32',
    Speed: 'float',
    ModalNextSpell: 'int32',
    StackAmount: 'int32',
    Totem_1: 'int32',
    Totem_2: 'int32',
    Reagent_1: 'int32',
    Reagent_2: 'int32',
    Reagent_3: 'int32',
    Reagent_4: 'int32',
    Reagent_5: 'int32',
    Reagent_6: 'int32',
    Reagent_7: 'int32',
    Reagent_8: 'int32',
    ReagentCount_1: 'int32',
    ReagentCount_2: 'int32',
    ReagentCount_3: 'int32',
    ReagentCount_4: 'int32',
    ReagentCount_5: 'int32',
    ReagentCount_6: 'int32',
    ReagentCount_7: 'int32',
    ReagentCount_8: 'int32',
    EquippedItemClass: 'int32',
    EquippedItemSubclass: 'int32',
    EquippedItemInvType: 'int32',

    // Indexed Effects (Effect_1, Effect_2, Effect_3, etc.)
    Effect_1: 'int32',
    Effect_2: 'int32',
    Effect_3: 'int32',

    // Effect Die Sides (EffectDieSides_1, EffectDieSides_2, EffectDieSides_3, etc.)
    EffectDieSides_1: 'int32',
    EffectDieSides_2: 'int32',
    EffectDieSides_3: 'int32',

    // Effect Base Dice (EffectBaseDice_1, EffectBaseDice_2, EffectBaseDice_3, etc.)
    EffectBaseDice_1: 'int32',
    EffectBaseDice_2: 'int32',
    EffectBaseDice_3: 'int32',

    // Effect Dice Per Level (EffectDicePerLevel_1, EffectDicePerLevel_2, EffectDicePerLevel_3, etc.)
    EffectDicePerLevel_1: 'float',
    EffectDicePerLevel_2: 'float',
    EffectDicePerLevel_3: 'float',

    // Effect Real Points Per Level (EffectRealPointsPerLevel_1, EffectRealPointsPerLevel_2, EffectRealPointsPerLevel_3, etc.)
    EffectRealPointsPerLevel_1: 'float',
    EffectRealPointsPerLevel_2: 'float',
    EffectRealPointsPerLevel_3: 'float',

    // Effect Base Points (EffectBasePoints_1, EffectBasePoints_2, EffectBasePoints_3, etc.)
    EffectBasePoints_1: 'int32',
    EffectBasePoints_2: 'int32',
    EffectBasePoints_3: 'int32',

    // Effect Mechanic (EffectMechanic_1, EffectMechanic_2, EffectMechanic_3, etc.)
    EffectMechanic_1: 'int32',
    EffectMechanic_2: 'int32',
    EffectMechanic_3: 'int32',

    // Implicit Target A (ImplicitTargetA_1, ImplicitTargetA_2, ImplicitTargetA_3, etc.)
    ImplicitTargetA_1: 'int32',
    ImplicitTargetA_2: 'int32',
    ImplicitTargetA_3: 'int32',

    // Implicit Target B (ImplicitTargetB_1, ImplicitTargetB_2, ImplicitTargetB_3, etc.)
    ImplicitTargetB_1: 'int32',
    ImplicitTargetB_2: 'int32',
    ImplicitTargetB_3: 'int32',

    // Effect Radius Index (EffectRadiusIndex_1, EffectRadiusIndex_2, EffectRadiusIndex_3, etc.)
    EffectRadiusIndex_1: 'int32',
    EffectRadiusIndex_2: 'int32',
    EffectRadiusIndex_3: 'int32',

    // Effect Aura (EffectAura_1, EffectAura_2, EffectAura_3, etc.)
    EffectAura_1: 'int32',
    EffectAura_2: 'int32',
    EffectAura_3: 'int32',

    // Effect Amplitude (EffectAmplitude_1, EffectAmplitude_2, EffectAmplitude_3, etc.)
    EffectAmplitude_1: 'int32',
    EffectAmplitude_2: 'int32',
    EffectAmplitude_3: 'int32',

    // Effect Multiple Value (EffectMultipleValue_1, EffectMultipleValue_2, EffectMultipleValue_3, etc.)
    EffectMultipleValue_1: 'float',
    EffectMultipleValue_2: 'float',
    EffectMultipleValue_3: 'float',

    // Effect Chain Target (EffectChainTarget_1, EffectChainTarget_2, EffectChainTarget_3, etc.)
    EffectChainTarget_1: 'int32',
    EffectChainTarget_2: 'int32',
    EffectChainTarget_3: 'int32',

    // Effect Item Type (EffectItemType_1, EffectItemType_2, EffectItemType_3, etc.)
    EffectItemType_1: 'int32',
    EffectItemType_2: 'int32',
    EffectItemType_3: 'int32',

    // Effect Misc Value (EffectMiscValue_1, EffectMiscValue_2, EffectMiscValue_3, etc.)
    EffectMiscValue_1: 'int32',
    EffectMiscValue_2: 'int32',
    EffectMiscValue_3: 'int32',

    // Effect Trigger Spell (EffectTriggerSpell_1, EffectTriggerSpell_2, EffectTriggerSpell_3, etc.)
    EffectTriggerSpell_1: 'int32',
    EffectTriggerSpell_2: 'int32',
    EffectTriggerSpell_3: 'int32',

    // Effect Points Per Combo (EffectPointsPerCombo_1, EffectPointsPerCombo_2, EffectPointsPerCombo_3, etc.)
    EffectPointsPerCombo_1: 'float',
    EffectPointsPerCombo_2: 'float',
    EffectPointsPerCombo_3: 'float',
    SpellVisualID_1: 'int32',
    SpellVisualID_2: 'int32',
    SpellIconID: 'int32',
    ActiveIconID: 'int32',
    SpellPriority: 'int32',
    Name_enUS: 'string',
    Name_2: 'string',
    Name_3: 'string',
    Name_4: 'string',
    Name_5: 'string',
    Name_6: 'string',
    Name_7: 'string',
    Name_8: 'string',
    NameMask: 'int32',
    NameSubtext_enUS: 'string',
    NameSubtext_2: 'string',
    NameSubtext_3: 'string',
    NameSubtext_4: 'string',
    NameSubtext_5: 'string',
    NameSubtext_6: 'string',
    NameSubtext_7: 'string',
    NameSubtext_8: 'string',
    NameSubtextMask: 'int32',
    Description_enUS: 'string',
    Description_2: 'string',
    Description_3: 'string',
    Description_4: 'string',
    Description_5: 'string',
    Description_6: 'string',
    Description_7: 'string',
    Description_8: 'string',
    DescriptionMask: 'int32',
    AuraDescription_enUS: 'string',
    AuraDescription_2: 'string',
    AuraDescription_3: 'string',
    AuraDescription_4: 'string',
    AuraDescription_5: 'string',
    AuraDescription_6: 'string',
    AuraDescription_7: 'string',
    AuraDescription_8: 'string',
    AuraDescriptionMask: 'int32',
    ManaCostPct: 'int32',
    StartRecoveryCategory: 'int32',
    StartRecoveryTime: 'int32',
    MaxTargetLevel: 'int32',
    SpellClassSet: 'int32',
    SpellClassMask_1: 'int32',
    SpellClassMask_2: 'int32',
    MaxTargets: 'int32',
    DefenseType: 'int32',
    PreventionType: 'int32',
    StanceBarOrder: 'int32',
    DamageMultiplier_1: 'float',
    DamageMultiplier_2: 'float',
    DamageMultiplier_3: 'float',
    MinFactionID: 'int32',
    MinReputation: 'int32',
    RequiredAuraVision: 'int32',
};